### ISSUE TITLE
Problem: User Superset

### ISSUE THREAD

**Issue by BennerLukas** [ArsalanSahab/Docker_Data_Science_Stack#1]
Hey. I would like to check your project out myself. By following your guide i encountered some problems.

```
021-01-03 14:41:41.262 UTC [113] FATAL:  password authentication failed for user "superset"
postgres_1   | 2021-01-03 14:41:41.262 UTC [113] DETAIL:  Role "superset" does not exist.
postgres_1   |  Connection matched pg_hba.conf line 99: "host all all all md5"
```

There is a problem with superset. It havent created something it needs to and so a lot of following problems occured and now I think I'm stuck in a boot loop of the docker-compose command.

Is there anything to consider to use the superset? I'm using windows and it's maybe a command that is not supported there?

**Comment by ArsalanSahab** [comment]
Hi Benner,

The repository hasn’t been updated in a while, I will retrospect on your issue and try to fix this.

This seems like an issue with authentication in superset.

Thank you so much for pointing this out.

**Comment by ArsalanSahab** [comment]
Hey @BennerLukas ,

I have ran all the containers again and have not encountered any issues, the whole concept of docker is that it eliminates the problems of “ Doesn’t work on my machine”, so rest assured it isn’t any issue with windows or macOS or Linux.

It seems that you have either entered the wrong credentials for superset, default credentials are mentioned in the README file or have have not yet understood how to access containers properly.

Please try to enter the correct credentials, if the problem persists then please post all the steps to reproduce with snapshots  if possible.

**Comment by BennerLukas** [comment]
Yes thats the great thing with docker... when it works.

I will retry it on a ubuntu server, because credentials or wrong use should be the issue I followed your README.

But thanks for helping :)

**Comment by ArsalanSahab** [comment]
Hi @BennerLukas ,

Sure try with Ubuntu server.

Feel free to reach me again if the problem persists.

I am closing this issue.
